# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MemberDataUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MemberData(object):
    def setupUi(self, MemberData):
        MemberData.setObjectName("MemberData")
        MemberData.setWindowModality(QtCore.Qt.ApplicationModal)
        MemberData.resize(300, 600)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        MemberData.setFont(font)
        self.saveInOutButton = QtWidgets.QPushButton(MemberData)
        self.saveInOutButton.setGeometry(QtCore.QRect(100, 550, 100, 40))
        self.saveInOutButton.setObjectName("saveInOutButton")
        self.label_2 = QtWidgets.QLabel(MemberData)
        self.label_2.setGeometry(QtCore.QRect(100, 409, 100, 25))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(MemberData)
        self.label_3.setGeometry(QtCore.QRect(100, 480, 100, 25))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.inDateEdit = QtWidgets.QDateTimeEdit(MemberData)
        self.inDateEdit.setGeometry(QtCore.QRect(50, 440, 200, 24))
        self.inDateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.inDateEdit.setObjectName("inDateEdit")
        self.outDateEdit = QtWidgets.QDateTimeEdit(MemberData)
        self.outDateEdit.setGeometry(QtCore.QRect(50, 510, 200, 24))
        self.outDateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.outDateEdit.setObjectName("outDateEdit")
        self.nameLabel = QtWidgets.QLabel(MemberData)
        self.nameLabel.setGeometry(QtCore.QRect(75, 10, 150, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel.setFont(font)
        self.nameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel.setObjectName("nameLabel")
        self.label_4 = QtWidgets.QLabel(MemberData)
        self.label_4.setGeometry(QtCore.QRect(100, 60, 100, 25))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.emailEdit = QtWidgets.QLineEdit(MemberData)
        self.emailEdit.setGeometry(QtCore.QRect(50, 90, 200, 24))
        self.emailEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.emailEdit.setObjectName("emailEdit")
        self.bankCardEdit = QtWidgets.QLineEdit(MemberData)
        self.bankCardEdit.setGeometry(QtCore.QRect(50, 160, 200, 24))
        self.bankCardEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.bankCardEdit.setObjectName("bankCardEdit")
        self.label_5 = QtWidgets.QLabel(MemberData)
        self.label_5.setGeometry(QtCore.QRect(100, 130, 100, 25))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.department_1_Edit = QtWidgets.QLineEdit(MemberData)
        self.department_1_Edit.setGeometry(QtCore.QRect(50, 300, 200, 24))
        self.department_1_Edit.setAlignment(QtCore.Qt.AlignCenter)
        self.department_1_Edit.setObjectName("department_1_Edit")
        self.label_6 = QtWidgets.QLabel(MemberData)
        self.label_6.setGeometry(QtCore.QRect(100, 270, 100, 25))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.professionEdit = QtWidgets.QLineEdit(MemberData)
        self.professionEdit.setGeometry(QtCore.QRect(50, 230, 200, 24))
        self.professionEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.professionEdit.setObjectName("professionEdit")
        self.label_7 = QtWidgets.QLabel(MemberData)
        self.label_7.setGeometry(QtCore.QRect(100, 200, 100, 25))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.department_2_Edit = QtWidgets.QLineEdit(MemberData)
        self.department_2_Edit.setGeometry(QtCore.QRect(50, 370, 200, 24))
        self.department_2_Edit.setAlignment(QtCore.Qt.AlignCenter)
        self.department_2_Edit.setObjectName("department_2_Edit")
        self.label_8 = QtWidgets.QLabel(MemberData)
        self.label_8.setGeometry(QtCore.QRect(100, 340, 100, 25))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(MemberData)
        self.label.setGeometry(QtCore.QRect(254, 98, 10, 10))
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(MemberData)
        self.label_9.setGeometry(QtCore.QRect(255, 169, 10, 10))
        self.label_9.setObjectName("label_9")

        self.retranslateUi(MemberData)
        QtCore.QMetaObject.connectSlotsByName(MemberData)

    def retranslateUi(self, MemberData):
        _translate = QtCore.QCoreApplication.translate
        MemberData.setWindowTitle(_translate("MemberData", "员工信息"))
        self.saveInOutButton.setText(_translate("MemberData", "保存"))
        self.label_2.setText(_translate("MemberData", "入职时间"))
        self.label_3.setText(_translate("MemberData", "离职时间"))
        self.nameLabel.setText(_translate("MemberData", "李林聪"))
        self.label_4.setText(_translate("MemberData", "邮箱"))
        self.label_5.setText(_translate("MemberData", "银行卡号"))
        self.label_6.setText(_translate("MemberData", "部门1"))
        self.label_7.setText(_translate("MemberData", "职务"))
        self.label_8.setText(_translate("MemberData", "部门2"))
        self.label.setText(_translate("MemberData", "*"))
        self.label_9.setText(_translate("MemberData", "*"))
